services:
  code-reviewer:
    build: 
      context: .
      dockerfile: Dockerfile
      # 启用构建缓存
      cache_from:
        - code-reviewer:latest
      # 使用BuildKit并行构建
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "8080:8080"
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_URL=mysql+asyncmy://codesense_ai:123456@mysql:3306/codesense_ai
      - DEBUG=false
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config/config.yaml:ro
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL数据库
  mysql:
    image: mysql:lts
    environment:
      MYSQL_DATABASE: codesense_ai
      MYSQL_USER: codesense_ai
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "33060:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
